version: '3'
services:
  client:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_GOOGLE_CLIENT_ID=338149376648-75b64mui7mts4754ldh98k48ernv0o1n.apps.googleusercontent.co
      - REACT_APP_SERVER_API=http://localhost:4001/api/v1/
    # links:
    #   - server
  # client:
  #   image: natsu2001/server-webtodo:latest
  #   environment:
  #     - REACT_APP_GOOGLE_CLIENT_ID=338149376648-75b64mui7mts4754ldh98k48ernv0o1n.apps.googleusercontent.co
  #     - REACT_APP_SERVER_API=http://localhost:4001/api/v1/
  #   ports:
  #     - "3000:3000"
