version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_GOOGLE_CLIENT_ID=338149376648-75b64mui7mts4754ldh98k48ernv0o1n.apps.googleusercontent.co
      - REACT_APP_SERVER_API=http://localhost:4001/api/v1/
    links:
      - db
  server:
    image: natsu2001/server-webtodo:latest
    environment:
      - REACT_APP_GOOGLE_CLIENT_ID=338149376648-75b64mui7mts4754ldh98k48ernv0o1n.apps.googleusercontent.co
      - REACT_APP_SERVER_API=http://localhost:4001/api/v1/
    ports:
      - "4001:4001"
